spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2.console:
    enabled: true
    path: /h2-console

  datasource:
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # create-drop create update validate none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secretKey: three-dot-three # jwt 시크릿키

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /szs/**

logging: # 로깅
  level: # 로깅 레벨
    root: info # 로킹 레벨 설정
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG # 정확한 로그를 찍기 위함
    org.hibernate.SQL: DEBUG # 정확한 로그를 찍기 위함
    org.hibernate.type.descriptor.sql: info # Query 확인